pipeline {
  agent any 
  tools {
    maven 'M3'
  }
  stages {
    stage('checkout') {
      steps {
        git 'https://github.com/oville92/al-geek-v2.git'
      }
    }
    stage ('Package dto library') {
		steps {
				echo "=== Packaging al-geek-dto library ==="
                sh 'mvn -f libraries/al-geek-dto clean install -DskipTests'
        }
    }
    stage ('Package rest library') {
		steps {
				echo "=== Packaging al-geek-rest library ==="
                sh 'mvn -f libraries/al-geek-rest clean install -DskipTests'
        }
    }
    stage ('Package order-api application') {
		steps {
				echo "=== Packaging order-api application ==="
                sh 'mvn -f dao/order-api clean package -DskipTests'
        }
    }   
    stage ('Package order-manager application') {
		steps {
				echo "=== Packaging order-manager application ==="
                sh 'mvn -f business/order-manager clean package -DskipTests'
        }
    }   
    stage ('Create order package') {
		steps {
				echo "=== Packaging order-manager application ==="
				sh 'rm -rf order'
				sh 'mkdir order'
                sh 'cp dao/order-api/target/order-api*.jar order/order-api.jar'
                sh 'cp business/order-manager/target/order-manager*.jar order/order-mgr.jar'
				sh 'cp docker/order/* order'
        }
    }   
    stage ('Publish package through SSH') {
        steps{
            script {
				sshPublisher(publishers: [
					sshPublisherDesc(configName: 'aws-order-host', transfers: [
						sshTransfer(
							execCommand: '''
								echo "Docker Clean Up";
                                sudo docker stop order-cont || true;
                                sudo docker rm order-cont || true;
                                sudo docker rmi order-img || true;
                                sudo rm -rf order || true;
                                mkdir order
                                '''
                        ),
						sshTransfer(
							sourceFiles: "order/*",
							execCommand: '''
							    ls -l /home/ec2-user;
							'''
                        ),
						sshTransfer(
							execCommand: '''
								cd order;
								sudo docker build -t order-img;
								sudo docker run -d --name order-cont --env-file env.order -p 8280:8280 -p 8080:8080 order-img;
								ls -l /home/ec2-user/order;
							'''
                        )
                    ])
                ])
            }
        }
    }

  }
}